GET http://localhost:3000/subscribers
###
POST http://localhost:3000/subscribers\
Content-Type: application/json
{
    "maerialname": "",
    "materialcode":"",
    "materialprice":"",
    "materialstock":""
}

###
DELETE http://localhost:3000/subscribers


